
import { jsPDF } from 'jspdf';
import { PredictionResult, AlzheimerStage } from '../types';

export const downloadReport = (prediction: PredictionResult) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(59, 130, 246); // Blue
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('ALZCARE MEDICAL REPORT', 20, 25);
  
  doc.setFontSize(10);
  doc.text(`REPORT ID: ${prediction.id}`, 140, 25);

  // Content
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  
  const startY = 60;
  doc.text('PATIENT INFORMATION', 20, startY);
  doc.line(20, startY + 2, 190, startY + 2);
  
  doc.text(`Patient ID: ALZ-9921-X`, 20, startY + 12);
  doc.text(`Timestamp: ${new Date(prediction.timestamp).toLocaleString()}`, 20, startY + 22);
  
  doc.text('DIAGNOSTIC ANALYSIS', 20, startY + 42);
  doc.line(20, startY + 44, 190, startY + 44);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Detected Alzheimer Stage:', 20, startY + 54);
  doc.setTextColor(239, 68, 68); // Red-ish
  doc.text(prediction.stage, 80, startY + 54);
  
  doc.setTextColor(51, 65, 85);
  doc.text('AI Inference Confidence:', 20, startY + 64);
  doc.text(`${(prediction.confidence * 100).toFixed(2)}%`, 80, startY + 64);
  
  doc.setFont('helvetica', 'normal');
  const clinicalDesc = `The automated CNN analysis for scan ${prediction.id} indicates structural markers consistent with the ${prediction.stage} phase of Alzheimer's Disease. This corresponds to the neuroimaging voxel intensity variances and hippocampal volume analysis performed by the AlZCARE AI engine.`;
  
  const splitDesc = doc.splitTextToSize(clinicalDesc, 170);
  doc.text(splitDesc, 20, startY + 80);

  // Footer / Disclaimer
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  const disclaimer = "DISCLAIMER: This report is generated by an artificial intelligence model and is intended for clinical decision support only. It does not constitute a definitive medical diagnosis. A review by a qualified neurologist or radiologist is required.";
  const splitDisclaimer = doc.splitTextToSize(disclaimer, 170);
  doc.text(splitDisclaimer, 20, 260);
  
  doc.save(`ALZCARE_Report_${prediction.id}.pdf`);
};

export const downloadGlobalReport = (history: PredictionResult[]) => {
  if (history.length === 0) return;
  const doc = new jsPDF();
  const latest = history[0];

  // Professional Header
  doc.setFillColor(30, 41, 59); // Slate-900
  doc.rect(0, 0, 210, 50, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(26);
  doc.setFont('helvetica', 'bold');
  doc.text('ALZCARE CLINICAL ARCHIVE', 20, 30);
  doc.setFontSize(10);
  doc.text('LONGITUDINAL PATIENT TRACKING SUMMARY', 20, 40);

  // Summary Box
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(14);
  doc.text('EXECUTIVE SUMMARY', 20, 65);
  doc.line(20, 67, 190, 67);

  doc.setFontSize(11);
  doc.text(`Patient Reference: ALZ-9921-X`, 20, 75);
  doc.text(`Total Analyses Performed: ${history.length}`, 20, 82);
  doc.text(`Current Condition: ${latest.stage}`, 20, 89);
  doc.text(`Report Generated: ${new Date().toLocaleString()}`, 20, 96);

  // History Table
  doc.setFontSize(14);
  doc.text('ANALYSIS TIMELINE', 20, 115);
  doc.line(20, 117, 190, 117);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Date', 25, 125);
  doc.text('Classification Stage', 80, 125);
  doc.text('Inference Fidelity', 150, 125);
  doc.setFont('helvetica', 'normal');

  let currentY = 135;
  history.forEach((record, index) => {
    if (currentY > 270) {
      doc.addPage();
      currentY = 20;
    }
    const dateStr = new Date(record.timestamp).toLocaleDateString();
    doc.text(dateStr, 25, currentY);
    doc.text(record.stage, 80, currentY);
    doc.text(`${(record.confidence * 100).toFixed(1)}%`, 150, currentY);
    currentY += 10;
  });

  // Trend Analysis
  if (currentY > 240) { doc.addPage(); currentY = 20; }
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('AI CLINICAL TREND NOTES', 20, currentY + 20);
  doc.line(20, currentY + 22, 190, currentY + 22);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const trendText = `Based on the longitudinal data provided above, the patient shows a recorded history of ${history.length} scans. The most recent assessment indicates a ${latest.stage} status. Clinicians should observe the interval between these data points to assess the rate of neurodegeneration.`;
  const splitTrend = doc.splitTextToSize(trendText, 170);
  doc.text(splitTrend, 20, currentY + 32);

  doc.save(`ALZCARE_Global_Archive_ALZ9921X.pdf`);
};
